services:
  job_scraper_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SELENIUM_URL=http://selenium_chrome:4444/wd/hub
    depends_on:
      selenium_chrome:
        condition: service_healthy
    restart: unless-stopped

    volumes:
      - .:/app   # ðŸ”¥ IMPORTANT â†’ live reload

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  selenium_chrome:
    image: selenium/standalone-chrome:4
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
