[project]
name = "job-scraper-api"
version = "0.1.0"
description = "Scraping backend engine"
requires-python = ">=3.10"

dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic",
  "python-dotenv",
  "loguru",
  "sqlalchemy",
  "psycopg2-binary"
]
